### PR TITLE
Resolve errno to meaningful string

### PR DESCRIPTION
**Pull request by cstruct**
This fixes santigimeno/node-ioctl#5

### CODE REVIEW

**Comment by santigimeno** [comment]
@cstruct Hi! thanks for the contribution.
I understand your reasoning, but I'm not too sure if this is the correct approach. I think having the exact code errno value can be very useful from a logical point of view: you can perform some actions when certain errno is returned, whilst using a string for this can be more tricky. Maybe returning an error object with the typical nodejs format is a better option. Something like this:
```
{
  code: 'EIVALDO',
  msg: 'Invalid domain',
  errno: 148
}
```
What do you think?

**Comment by cstruct** [comment]
I think that's a much better solution. Although when thinking about this I think it would be better to do a more major API change. This since this would be a breaking change either way. 

If one looks at synchronous core APIs they never return a code or a `Error`. I think this should have no return value but throw on Error, `return Nan::ThrowError(Nan::ErrnoException(errno, NULL, NULL, NULL));`.

Or would this be too major of a change?

**Comment by LinusU** [comment]
Change the first NULL to the string "ioctl", then that will show up under the `syscall` property of the error...

**Comment by santigimeno** [comment]
The change itself LGTM. I'm on the fence on this though. IMHO, returning the error would not be as a breaking change as just throwing. I'm going to ping the known [dependents](https://www.npmjs.com/browse/depended/ioctl) for their input.

FWIW I'm +1 on this change.

/cc @denghongcai @joeferner @omeryagmurlu @brghena @abresas

**Comment by santigimeno** [comment]
I forgot. Modifications in the `README` and examples would be needed

**Comment by cstruct** [comment]
When reading up a bit more on `ioctl` I can see my approach here is a bit naive.

> Decent ioctls return 0 on success and -1 on error, while any output
> value is stored via the argument.  However, **quite a few ioctls in
> fact return an output value**.
>
> &mdash; <cite>[IOCTL_LIST(2)](http://man7.org/linux/man-pages/man2/ioctl_list.2.html)</cite>

The current approach I take ignores the case of actual return values from `ioctl`. I will take another stab at this.

**Comment by cstruct** [comment]
@santigimeno: Care to re-review?

- I no longer ignore `ioctl` return value.
- API is a lot closer to the current (Almost identical to the old except for resolved `errno` message?)
- Added a basic API documentation

**Comment by santigimeno** [comment]
LGTM. Could you squash it into a single commit? Thanks!!!

**Comment by cstruct** [comment]
Butternut Squash

**Comment by santigimeno** [comment]
Landed in https://github.com/santigimeno/node-ioctl/commit/349a9bca704021039e5c46f57fe988ba0e9baa78.

Published as `2.0.0`. Thanks @cstruct !

**Pull request merged**
